### ISSUE TITLE
Misunderstanding of TTL param?

### ISSUE THREAD

**Issue by devonliu02** [matthiasmullie/psr16-integration-tests#1]
In tests, the **TTL** param in second looks like **Expiration** param according to PSR-16, am i wrong?

**Comment by matthiasmullie** [comment]
You are correct, seems like an oversight on my part.
Anyway, I would suggest not to rely on this repo (I don't even use it to test my own cache library). It was nothing more than a "start", but there's alternatives that are more complete/correct. I will make that more clear by updating the README.
